import { APP_PREFIX_PATH } from "constants/route.constant";
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";
import { ADMIN, USER } from "constants/roles.constant";

const appsNavigationConfig = [
  {
    key: "menu",
    path: "",
    title: "menu",
    translateKey: "menu",
    icon: "apps",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: "account",
        path: "",
        title: "YOUR ACCOUNT",
        translateKey: "account",
        icon: "account",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "account.profile",
            path: `/app/account/settings/profile`,
            title: "Create Profile",
            translateKey: "nav.account.profile",
            icon: "account",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "account.profile.settings",
            path: `/app/account/settings/profile`,
            title: "Settings",
            translateKey: "nav.account.profile.settings",
            icon: "account",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "dashboard",
        path: "",
        title: "DASHBOARD",
        translateKey: "dashboard",
        icon: "dashboard",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "dashboard.users",
            path: ``,
            title: "Map Of Users",
            translateKey: "nav.dashboard.users",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "dashboard.users",
            path: ``,
            title: "User Statistics",
            translateKey: "nav.dashboard.users",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "dashboard.reminders",
            path: ``,
            title: "Reminders/To-Do List",
            translateKey: "nav.dashboard.reminders",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "services",
        path: "",
        title: "SERVICES",
        translateKey: "services",
        icon: "apps",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "services.socialMedia",
            path: `/services/social-media`,
            title: "Social Media Tools",
            translateKey: "nav.socialMedia.socialMediaServ",
            icon: "project",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "services.marketing",
            path: "/services/marketing-tools",
            title: "Marketing Tools",
            translateKey: "nav.marketing",
            icon: "sales",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "services.business",
            path: "/services/business",
            title: "Business Tools",
            translateKey: "nav.business",
            icon: "crm",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "services.writingTools",
            path: "/services/writing-tools",
            title: "Writing Tools",
            translateKey: "nav.writingTools",
            icon: "guide",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "services.miscellaneous",
            path: `/services/miscellaneous`,
            title: "Miscellaneous",
            translateKey: "nav.miscellaneous",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [
              // {
              // 	key: 'miscellaneous.dashboard',
              // 	path: `services/miscellaneous`,
              // 	title: 'All Miscellaneous Services',
              // 	translateKey: 'nav.miscellaneous.all',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.Latter',
              // 	path: `services/miscellaneous/cover-latter`,
              // 	title: 'Cover Latter',
              // 	translateKey: 'nav.miscellaneous.Cover',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.fictional',
              // 	path: `services/miscellaneous/fictional-story`,
              // 	title: 'Fictional Story Ideas',
              // 	translateKey: 'nav.miscellaneous.fictional',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.recipe',
              // 	path: `services/miscellaneous/food-recipe`,
              // 	title: 'Food Recipes',
              // 	translateKey: 'nav.miscellaneous.recipe',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.quora',
              // 	path: `services/miscellaneous/quora-answers`,
              // 	title: 'Quora Answers',
              // 	translateKey: 'nav.miscellaneous.quora',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.greetings',
              // 	path: `services/miscellaneous/greetings`,
              // 	title: 'Greetings',
              // 	translateKey: 'nav.miscellaneous.greetings',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.song',
              // 	path: `services/miscellaneous/song-lyrics`,
              // 	title: 'Song Lyrics',
              // 	translateKey: 'nav.miscellaneous.song',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.Job',
              // 	path: `services/miscellaneous/job-description`,
              // 	title: 'Job Descriptions',
              // 	translateKey: 'nav.miscellaneous.Job',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.pdDes',
              // 	path: `services/miscellaneous/pd-reviews`,
              // 	title: 'Product Reviews',
              // 	translateKey: 'nav.miscellaneous.pdDes',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // },
              // {
              // 	key: 'miscellaneous.linkedinbio',
              // 	path: `services/miscellaneous/linkedin-bio`,
              // 	title: 'Personal Linkedin Bio',
              // 	translateKey: 'nav.miscellaneous.linkedinbio',
              // 	icon: '',
              // 	type: NAV_ITEM_TYPE_ITEM,
              // 	authority: [ADMIN, USER],
              // 	subMenu: []
              // }
            ],
          },
          {
            key: "services.allServices",
            path: "/services/all-services",
            title: "All Our Services",
            translateKey: "nav.allServices",
            icon: "dashboard",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          //   {
          //     key: "apps.crypto",
          //     path: "",
          //     title: "demo",
          //     translateKey: "nav.Descriptions.crypto",
          //     icon: "crypto",
          //     type: NAV_ITEM_TYPE_COLLAPSE,
          //     authority: [ADMIN, USER],
          //     subMenu: [
          //       // 	{
          //       // 		key: 'appsCrypto.dashboard',
          //       // 		path: `${APP_PREFIX_PATH}/crypto/dashboard`,
          //       // 		title: 'Dashboard',
          //       // 		translateKey: 'nav.appsCrypto.dashboard',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsCrypto.portfolio',
          //       // 		path: `${APP_PREFIX_PATH}/crypto/portfolio`,
          //       // 		title: 'Portfolio',
          //       // 		translateKey: 'nav.appsCrypto.portfolio',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsCrypto.market',
          //       // 		path: `${APP_PREFIX_PATH}/crypto/market`,
          //       // 		title: 'Market',
          //       // 		translateKey: 'nav.appsCrypto.market',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsCrypto.wallets',
          //       // 		path: `${APP_PREFIX_PATH}/crypto/wallets`,
          //       // 		title: 'Wallets',
          //       // 		translateKey: 'nav.appsCrypto.wallets',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //     ],
          //   },
          //   {
          //     key: "apps.knowledgeBase",
          //     path: "",
          //     title: "demo",
          //     translateKey: "nav.Ideas.knowledgeBase",
          //     icon: "knowledgeBase",
          //     type: NAV_ITEM_TYPE_COLLAPSE,
          //     authority: [ADMIN, USER],
          //     subMenu: [
          //       // 	{
          //       // 		key: 'appsknowledgeBase.helpCenter',
          //       // 		path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
          //       // 		title: 'Help Center',
          //       // 		translateKey: 'nav.appsknowledgeBase.helpCenter',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsknowledgeBase.article',
          //       // 		path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
          //       // 		title: 'Article',
          //       // 		translateKey: 'nav.appsknowledgeBase.article',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsknowledgeBase.manageArticles',
          //       // 		path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
          //       // 		title: 'Manage Articles',
          //       // 		translateKey: 'nav.appsknowledgeBase.manageArticles',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsknowledgeBase.editArticle',
          //       // 		path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
          //       // 		title: 'Edit Article',
          //       // 		translateKey: 'nav.appsknowledgeBase.editArticle',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //     ],
          //   },
          //   {
          //     key: "apps.account",
          //     path: "",
          //     title: "demo",
          //     translateKey: "nav.Titles.account",
          //     icon: "account",
          //     type: NAV_ITEM_TYPE_COLLAPSE,
          //     authority: [ADMIN, USER],
          //     subMenu: [
          //       // 	{
          //       // 		key: 'appsAccount.settings',
          //       // 		path: `${APP_PREFIX_PATH}/account/settings/profile`,
          //       // 		title: 'Settings',
          //       // 		translateKey: 'nav.appsAccount.settings',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsAccount.invoice',
          //       // 		path: `${APP_PREFIX_PATH}/account/invoice/36223`,
          //       // 		title: 'Invoice',
          //       // 		translateKey: 'nav.appsAccount.invoice',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsAccount.activityLog',
          //       // 		path: `${APP_PREFIX_PATH}/account/activity-log`,
          //       // 		title: 'Activity Log',
          //       // 		translateKey: 'nav.appsAccount.activityLog',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //       // 	{
          //       // 		key: 'appsAccount.kycForm',
          //       // 		path: `${APP_PREFIX_PATH}/account/kyc-form`,
          //       // 		title: 'KYC Form',
          //       // 		translateKey: 'nav.appsAccount.kycForm',
          //       // 		icon: '',
          //       // 		type: NAV_ITEM_TYPE_ITEM,
          //       // 		authority: [ADMIN, USER],
          //       // 		subMenu: []
          //       // 	},
          //     ],
          //   },
        ],
      },
      {
        key: "project",
        path: "",
        title: "PROJECT MANAGEMENT",
        translateKey: "project",
        icon: "project",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "project.current",
            path: ``,
            title: "Current Projects",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.past",
            path: ``,
            title: "Past Projects",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.favorites",
            path: ``,
            title: "Favorites",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.top.searched.questions",
            path: ``,
            title: "Top Searched Questions",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.top.searched.topics",
            path: ``,
            title: "Top Searched Topics",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.top.searched.services",
            path: ``,
            title: "Top Searched Services",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.top.searched.words",
            path: ``,
            title: "Top Searched Words",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "project.top.used.tools",
            path: ``,
            title: "Top Used Tools",
            translateKey: "nav.dashboard.projects",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "content",
        path: "",
        title: "CONTENT ORGANIZER",
        translateKey: "content",
        icon: "dataDisplay",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "content.videos",
            path: ``,
            title: "Videos",
            translateKey: "nav.dashboard.content",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "content.photos",
            path: ``,
            title: "Photos",
            translateKey: "nav.dashboard.content",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "content.documents",
            path: ``,
            title: "Documents",
            translateKey: "nav.dashboard.content",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "communication",
        path: "",
        title: "COMMUNICATION",
        translateKey: "communication",
        icon: "communication",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "communication.instagram",
            path: ``,
            title: "Instagram",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "communication.tikTok",
            path: ``,
            title: "Tik-Tok",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "communication.facebook",
            path: ``,
            title: "Facebook",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "communication.twitter",
            path: ``,
            title: "Twitter",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "communication.linkedin",
            path: ``,
            title: "LinkedIn",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "communication.youtube",
            path: ``,
            title: "Youtube",
            translateKey: "nav.dashboard.communication",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "socialMedia",
        path: "",
        title: "SOCIAL MEDIA MANAGER",
        translateKey: "socialMedia",
        icon: "socialMedia",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "socialMedia.instagram",
            path: ``,
            title: "Instagram",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "socialMedia.tikTok",
            path: ``,
            title: "Tik-Tok",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "socialMedia.facebook",
            path: ``,
            title: "Facebook",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "socialMedia.twitter",
            path: ``,
            title: "Twitter",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "socialMedia.linkedin",
            path: ``,
            title: "LinkedIn",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "socialMedia.youtube",
            path: ``,
            title: "Youtube",
            translateKey: "nav.dashboard.socialMedia",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "analytics",
        path: "",
        title: "AI ANALYTICS",
        translateKey: "analytics",
        icon: "graph",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "analytics.allReports",
            path: ``,
            title: "All Reports",
            translateKey: "nav.dashboard.analytics",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "analytics.pastReports",
            path: ``,
            title: "Past Reports",
            translateKey: "nav.dashboard.analytics",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "analytics.industry",
            path: ``,
            title: "Industry Benchmarking",
            translateKey: "nav.dashboard.analytics",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "analytics.statistics",
            path: ``,
            title: "Post Statistics",
            translateKey: "nav.dashboard.analytics",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "knowledgeBase",
        path: "",
        title: "KNOWLEDGE BASE",
        translateKey: "knowledgeBase",
        icon: "knowledgeBase",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "knowledgeBase.articles",
            path: ``,
            title: "Articles",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "knowledgeBase.upcomingServices",
            path: ``,
            title: "Upcoming Services",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "knowledgeBase.roadmap",
            path: ``,
            title: "Roadmap",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "knowledgeBase.inspiration",
            path: ``,
            title: "Inspiration",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "knowledgeBase.community",
            path: ``,
            title: "Community",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "knowledgeBase.resources",
            path: ``,
            title: "Resources",
            translateKey: "nav.dashboard.knowledgeBase",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "newsletter",
        path: "",
        title: "NEWSLETTER RELEASE",
        translateKey: "newsletter",
        icon: "envelopeOpen",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "newsletter.campaign",
            path: ``,
            title: "Campaign",
            translateKey: "nav.dashboard.newsletter",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "newsletter.audiences",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.newsletter",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "royaltyProgram",
        path: "",
        title: "ROYALTY PROGRAM",
        translateKey: "royaltyProgram",
        icon: "gift",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: "royaltyProgram.",
            path: ``,
            title: "Audiences",
            translateKey: "nav.dashboard.royaltyProgram",
            icon: "apps",
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: "team",
        path: "",
        title: "TEAM",
        translateKey: "team",
        icon: "crm",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: "support",
        path: "",
        title: "SUPPORT AND RESOURCES",
        translateKey: "support",
        icon: "support",
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [],
      },
    ],
  },
];

export default appsNavigationConfig;
