import React from 'react'
import {
    HiOutlineChartSquareBar,
    HiOutlineUserGroup,
    HiOutlineTrendingUp,
    HiOutlineUserCircle,
    HiOutlineBookOpen,
    HiOutlineCurrencyDollar,
    HiOutlineShieldCheck,
    HiOutlineColorSwatch,
    HiOutlineChatAlt,
    HiOutlineDesktopComputer,
    HiOutlinePaperAirplane,
    HiOutlineChartPie,
    HiOutlineUserAdd,
    HiOutlineKey,
    HiOutlineBan,
    HiOutlineHand,
    HiOutlineDocumentText,
    HiOutlineTemplate,
    HiOutlineLockClosed,
    HiOutlineDocumentDuplicate,
    HiOutlineViewGridAdd,
    HiOutlineShare,
    HiOutlineVariable,
    HiOutlineCode
} from 'react-icons/hi'
import {
    FcBusinessman,
    FcEditImage,
    FcNews,
    FcIdea,
    FcViewDetails,
    FcVideoCall,
    FcDocument,
    FcRegisteredTrademark,
    FcMoneyTransfer,
    FcBullish,
    FcRules,
    FcSurvey,
    FcPositiveDynamic,
    FcServices,
} from 'react-icons/fc'

const navigationIcon = {
    FcEditImage: <FcEditImage />,
    FcBusinessman: <FcBusinessman />,
    FcNews: <FcNews />,
    FcIdea: <FcIdea />,
    FcViewDetails: <FcViewDetails />,
    FcVideoCall: <FcVideoCall />,
    FcDocument: <FcDocument />,
    FcRegisteredTrademark: <FcRegisteredTrademark />,
    FcMoneyTransfer: <FcMoneyTransfer />,
    FcBullish: <FcBullish />,
    FcRules: <FcRules />,
    FcSurvey: <FcSurvey />,
    FcPositiveDynamic: <FcPositiveDynamic />,
    FcServices: <FcServices />,


    apps: <HiOutlineViewGridAdd />,
    project: <HiOutlineChartSquareBar />,
    crm: <HiOutlineUserGroup />,
    sales: <HiOutlineTrendingUp />,
    crypto: <HiOutlineCurrencyDollar />,
    knowledgeBase: <HiOutlineBookOpen />,
    account: <HiOutlineUserCircle />,
    uiComponents: <HiOutlineTemplate />,
    common: <HiOutlineColorSwatch />,
    feedback: <HiOutlineChatAlt />,
    dataDisplay: <HiOutlineDesktopComputer />,
    forms: <HiOutlineDocumentText />,
    navigation: <HiOutlinePaperAirplane />,
    graph: <HiOutlineChartPie />,
    authentication: <HiOutlineLockClosed />,
    signIn: <HiOutlineShieldCheck />,
    signUp: <HiOutlineUserAdd />,
    forgotPassword: <HiOutlineLockClosed />,
    resetPassword: <HiOutlineKey />,
    pages: <HiOutlineDocumentDuplicate />,
    welcome: <HiOutlineHand />,
    accessDenied: <HiOutlineBan />,
    guide: <HiOutlineBookOpen />,
    documentation: <HiOutlineDocumentText />,
    sharedComponentDoc: <HiOutlineShare />,
    utilsDoc: <HiOutlineVariable />,
    changeLog: <HiOutlineCode />
}

export default navigationIcon