import React from "react";
import {
  HiOutlineChartSquareBar,
  HiOutlineUserGroup,
  HiOutlineTrendingUp,
  HiOutlineUserCircle,
  HiOutlineBookOpen,
  HiOutlineCurrencyDollar,
  HiOutlineShieldCheck,
  HiOutlineColorSwatch,
  HiOutlineChatAlt,
  HiOutlineDesktopComputer,
  HiOutlinePaperAirplane,
  HiOutlineChartPie,
  HiOutlineUserAdd,
  HiOutlineKey,
  HiOutlineBan,
  HiOutlineHand,
  HiOutlineDocumentText,
  HiOutlineTemplate,
  HiOutlineLockClosed,
  HiOutlineDocumentDuplicate,
  HiOutlineViewGridAdd,
  HiOutlineShare,
  HiOutlineVariable,
  HiOutlineCode,
  HiOutlineViewGrid,
} from "react-icons/hi";
import {
  FcBusinessman,
  FcEditImage,
  FcNews,
  FcIdea,
  FcViewDetails,
  FcVideoCall,
  FcDocument,
  FcRegisteredTrademark,
  FcMoneyTransfer,
  FcBullish,
  FcRules,
  FcSurvey,
  FcPositiveDynamic,
  FcServices,
  FcKindle,
  FcHeadset,
  FcFinePrint,
  FcBusiness,
  FcReading,
  FcPaid,
  FcComments,
  FcTemplate,
  FcStatistics,
  FcManager,
  FcPortraitMode,
  FcAdvertising,
  FcLink,
  FcNook,
  FcList,
  FcSalesPerformance,
  FcGoogle,
  FcFeedback,
  FcSmartphoneTablet,
  FcRating,
  FcFaq,
  FcTodoList,
  FcRatings,
  FcStackOfPhotos,
  FcProcess,
  FcOpenedFolder,
  FcPrint,
  FcDiploma2,
} from "react-icons/fc";

import { AiFillAmazonCircle } from "react-icons/ai";
const navigationIcon = {
  FcEditImage: <FcEditImage />,
  FcBusinessman: <FcBusinessman />,
  FcNews: <FcNews />,
  FcIdea: <FcIdea />,
  FcViewDetails: <FcViewDetails />,
  FcVideoCall: <FcVideoCall />,
  FcLink: <FcLink />,
  FcDocument: <FcDocument />,
  FcRegisteredTrademark: <FcRegisteredTrademark />,
  FcMoneyTransfer: <FcMoneyTransfer />,
  FcBullish: <FcBullish />,
  FcRules: <FcRules />,
  FcSurvey: <FcSurvey />,
  FcPositiveDynamic: <FcPositiveDynamic />,
  FcServices: <FcServices />,
  FcKindle: <FcKindle />,
  FcFinePrint: <FcFinePrint />,
  FcHeadset: <FcHeadset />,
  FcBusiness: <FcBusiness />,
  FcReading: <FcReading />,
  FcPaid: <FcPaid />,
  FcComments: <FcComments />,
  FcTemplate: <FcTemplate />,
  FcManager: <FcManager />,
  FcPortraitMode: <FcPortraitMode />,
  FcAdvertising: <FcAdvertising />,
  FcNook: <FcNook />,
  FcList: <FcList />,
  FcStatistics: <FcStatistics />,
  FcSalesPerformance: <FcSalesPerformance />,
  FcGoogle: <FcGoogle />,
  FcFeedback: <FcFeedback />,
  FcFaq: <FcFaq />,
  FcSmartphoneTablet: <FcSmartphoneTablet />,
  FcRating: <FcRating />,
  FcTodoList: <FcTodoList />,
  FcStackOfPhotos: <FcStackOfPhotos />,
  FcRatings: <FcRatings />,
  FcProcess: <FcProcess />,
  FcOpenedFolder: <FcOpenedFolder />,
  FcPrint: <FcPrint />,
  FcDiploma2: <FcDiploma2 />,

  apps: <HiOutlineViewGridAdd />,
  dashboard: <HiOutlineViewGrid />,
  project: <HiOutlineChartSquareBar />,
  crm: <HiOutlineUserGroup />,
  sales: <HiOutlineTrendingUp />,
  crypto: <HiOutlineCurrencyDollar />,
  knowledgeBase: <HiOutlineBookOpen />,
  account: <HiOutlineUserCircle />,
  uiComponents: <HiOutlineTemplate />,
  common: <HiOutlineColorSwatch />,
  feedback: <HiOutlineChatAlt />,
  dataDisplay: <HiOutlineDesktopComputer />,
  forms: <HiOutlineDocumentText />,
  navigation: <HiOutlinePaperAirplane />,
  graph: <HiOutlineChartPie />,
  authentication: <HiOutlineLockClosed />,
  signIn: <HiOutlineShieldCheck />,
  signUp: <HiOutlineUserAdd />,
  forgotPassword: <HiOutlineLockClosed />,
  resetPassword: <HiOutlineKey />,
  pages: <HiOutlineDocumentDuplicate />,
  welcome: <HiOutlineHand />,
  accessDenied: <HiOutlineBan />,
  guide: <HiOutlineBookOpen />,
  documentation: <HiOutlineDocumentText />,
  sharedComponentDoc: <HiOutlineShare />,
  utilsDoc: <HiOutlineVariable />,
  changeLog: <HiOutlineCode />,

  amazon: <AiFillAmazonCircle />,
};

export default navigationIcon;
